# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]

    encoders:
        Symfony\Component\Security\Core\User\User: 
            algorithm: bcrypt
            cost: 12

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory:
                users:
                    user:
                        password: $2a$12$oTsukZGZ25/BgY8bqm.lBeu5mil63FpkLui9XMPU5ZMbR9156w2ya
                        roles: 'ROLE_USER'
                    admin:
                        password: $2a$12$JrPZtmthV2sCB3PF/WccMOAJuljfe0Q2AYzOgGraiFBobmrCXShae
                        roles: 'ROLE_ADMIN'

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            form_login:
                login_path: /login
                check_path: /login_check
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
          
            logout:
                path:   /logout
                target: /
            
    access_control:
            # require ROLE_ADMIN for /admin*
            - { path: ^/admin, roles: ROLE_ADMIN }